### ISSUE TITLE
Script Not Working

### ISSUE THREAD

**Issue by juan-restrepo** [sqren/alfred-currency#4]
After typing exactly as requested
![image](https://user-images.githubusercontent.com/9620002/113430766-8ec7d780-938f-11eb-8990-7f4d15399f66.png)
it suggests other things to do instead of running the script
![image](https://user-images.githubusercontent.com/9620002/113430804-a737f200-938f-11eb-99fc-48c6c0d03015.png)

Are there any extra instructions needed to install?

**Comment by olgv** [comment]
Same here unfortunately :(

<img width="603" alt="Screenshot 2021-04-09 at 19 18 40" src="https://user-images.githubusercontent.com/5272004/114230271-798f1200-9968-11eb-8bd8-3e6d0a31e9a2.png">

I got a similar behaviour a while back but after syncing Alfred's preferences between computers somehow it got fixed. Now doesn't work on any of the machines...

A solution would be highly appreciated.
Thank you

**Comment by sorenlouv** [comment]
@olgv @juan-restrepo Can you try the latest version of the workflow and let me know if that works?

**Comment by juan-restrepo** [comment]
@sqren thank you! All good now

**Comment by olgv** [comment]
@sqren very much appreciated. 
Confirm it is working again, thank you.
